### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by LameName** [xplico/CapAnalysis#10]
Hey,

I clone the  repo and tried to build it but it didn't work. I simple try a 'make', because I can't find any configure/autogen or hint in the README what I should do before 'make'. But I get the error message: "make[1]: Entering directory '/home/pstengel/investigations/8com/project_8com/capanalysis/pcapseek'
make[1]: Leaving directory '/home/pstengel/investigations/8com/project_8com/capanalysis/pcapseek'
cc -rdynamic -I/home/pstengel/investigations/8com/project_8com/capanalysis/include -Wall -fPIC -D_FILE_OFFSET_BITS=64 -I/home/pstengel/investigations/8com/project_8com/capanalysis/include -I/usr/include/postgresql -g -ggdb -O0 -DXPL_X86=1 -c -o pkginstall.o pkginstall.c
pkginstall.c:32:20: fatal error: pkgbin.h: No such file or directory
compilation terminated.
Makefile:234: recipe for target 'pkginstall.o' failed
make: **\* [pkginstall.o] Error 1
"
What should I do?

Greets, Paul

**Comment by gnlcosta** [comment]
Hi,
to generate pkgbin.h you have to launch:
make pkgbin
You have also to clone xplico and compile it before CapAnalysis.

Ciao.
Gianluca
