### ISSUE TITLE
How to capture traffic from remote host "on-the-fly"?

### ISSUE THREAD

**Issue by MatejKovacic** [xplico/CapAnalysis#13]
Hi,

I am trying to capture traffic from remote host "on-the-fly". Remote host is RaspberryPi and I am using tcpdump. For capturing into Wireshark, it would work like this:

`ssh user@host "sudo tcpdump -i wlan0 -s 65535 -w - etr host 11:22:33:44:55:66" | wireshark -k -i -`

Anyway, I am trying to do similar with CapAnalysis:

`ssh user@host "sudo tcpdump -i wlan0 -s 65535 -w - etr host 11:22:33:44:55:66" | nc 127.0.0.1 30002`

It is working, however, data appear only when I stop capturing. Is it possible to do analysis and view graphs while still capturing data?

**Comment by gnlcosta** [comment]
Hi MatejKovacic,
no, you have to stop and restart the "nc" transmission.
I suggest you this script:
```

#!/bin/bash

(tcpdump -i wlan0 -s 65535 -w - etr host 11:22:33:44:55:66 | nc 127.0.0.1 30002) &
pid1=$!
sleep 30
    
while true; do
    (tcpdump -i wlan0 -s 65535 -w - etr host 11:22:33:44:55:66 | nc 127.0.0.1 30002) &
    pid2=$!
    sleep 2
    pkill -P $pid1
    sleep 30
    (tcpdump -i wlan0 -s 65535 -w - etr host 11:22:33:44:55:66 | nc 127.0.0.1 30002) &
    pid1=$!
    sleep 2
    pkill -P $pid2
    sleep 30
done

```
The packets overlap (repetition) is managed by CapAnalysis. The overlap guarantees the TCP connections.
