### ISSUE TITLE
Blank page after password set, Ubuntu desktop 18.04

### ISSUE THREAD

**Issue by RandyDavis74** [xplico/CapAnalysis#17]
Has anyone used CapAnalysis with Ubuntu desktop 18.04?  It appears to install correctly, the new password page works fine, comes back with green check marks however when clicking on the green "go to Capanalysis UI" the screen comes back blank.  When I look at the logs, /opt/capanalysis/log/2018_09_10.log, the message "error, user fail: Fatal: password authentication failed for user "capana" and Error: DB name fail: Fatal: database "capanalysis" does not exist.  

This looks like a configuration or setup with a newer release, I checked Apache2, firewall is open, latest release of php-pgsql is installed.  
 Thanks, Randy

9/12/2018 Subsequently, I was able to log into the capanalysis database, could see tables and columns.  It appeared the database setup ran fine.

**Comment by lfalconi** [comment]
Having the same issues here:

**Using:** 
Ubuntu 18.04.1 LTS Release:18.04 Codename: bionic

**output from log:**
ERROR: User fail: FATAL:  password authentication failed for user "capana"
FATAL:  password authentication failed for user "capana"

Apache and Postgree are running and apparently ok

**Comment by eberlou** [comment]
Same issue on Ubuntu 18.04.1

1. Once I click the "New password button", the "password authentication failed" stops.

`11:45:46 ERROR: User fail: FATAL:  password authentication failed for user "capana"
FATAL:  password authentication failed for user "capana"

11:45:46 INFO: DB version: 1.1
`
The Db and service seems to be Ok
![image](https://user-images.githubusercontent.com/33357341/45634849-7150ed80-ba71-11e8-9e61-750c634ccb2c.png)


2. When I hit http://127.0.0.1:9877

**/var/log/apache2/capana_error.log**
`[Mon Sep 17 11:46:19.566135 2018] [php7:error] [pid 30959] [client 127.0.0.1:40486] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /opt/capanalysis/www/lib/Cake/Core/Object.php on line 30
[Mon Sep 17 11:46:19.567595 2018] [php7:error] [pid 30959] [client 127.0.0.1:40486] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in /opt/capanalysis/www/lib/Cake/Error/ExceptionRenderer.php:177\nStack trace:\n#0 /opt/capanalysis/www/lib/Cake/Error/ExceptionRenderer.php(95): ExceptionRenderer->_getController(Object(InternalErrorException))\n#1 /opt/capanalysis/www/lib/Cake/Error/ErrorHandler.php(126): ExceptionRenderer->__construct(Object(InternalErrorException))\n#2 /opt/capanalysis/www/lib/Cake/Error/ErrorHandler.php(284): ErrorHandler::handleException(Object(InternalErrorException))\n#3 /opt/capanalysis/www/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', '/opt/capanalysi...', 30)\n#4 /opt/capanalysis/www/lib/Cake/Core/App.php(970): ErrorHandler::handleError(64, 'Cannot use 'Obj...', '/opt/capanalysi...', 30, Array)\n#5 /opt/capanalysis/www/lib/Cake/Core/App.php(943): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in /opt/capanalysis/www/lib/Cake/Error/ExceptionRenderer.php on line 177`

**Comment by crocodanser** [comment]
Same issue please do you have an idea to work with php 7.2?
gdebi install php 7.2 automatically and i think it's not compatible with it.
i tried too with a debian 9 with php 7.0 but i have another issue with pgsql.
Please could you explain us what is the requirements?
Thanx
Edit : on ubuntu 18.4 i switch to php 7.0 and i have an internal error
and no error in the log /var/log/apache2/capana_error.log 
![image](https://user-images.githubusercontent.com/3707736/49147072-8390a880-f2b8-11e8-994e-f701123bb8a4.png)

Some help please?

**Comment by gnlcosta** [comment]
Fixed (I hope) in the new [release](https://github.com/xplico/CapAnalysis/releases/tag/v1.2.3).
You can download the deb package [here]( https://sourceforge.net/projects/capanalysis/files/version%201.2.3/capanalysis_1.2.3_amd64.deb/download).

**Comment by svenseeberg** [comment]
I can confirm that the fix works for me (Ubuntu 18.04). Thanks.

**Comment by MatejKovacic** [comment]
I just installed capanalysis_1.2.3_amd64.deb on Ubuntu 18.04.2 LTS. Then I go to 
http://localhost:9877/capinstall/ and got this:
```
Install-Execution-Advice
CapAnalysis the user DB failed the authentication.

To change the user password click the button below.
New password
```

When I click to New password a page reloads and I have a button "Go to CapAnalysis UI". Stattus of CapAnalysis is Running and status of Database is Ok.

When I click to  "Go to CapAnalysis UI", I got blank page.

**Comment by MatejKovacic** [comment]
OK, I managed to solve this. The problem was, I was not using Gdebi packet manager...

**Comment by chen-299** [comment]
> OK, I managed to solve this. The problem was, I was not using Gdebi packet manager...

hello，I have the same problem.Could I get the methods of resolution from you？Please and thanks！

**Comment by chen-299** [comment]
> OK, I managed to solve this. The problem was, I was not using Gdebi packet manager...

hello，how to use Gdebi packet manager？

**Comment by MatejKovacic** [comment]
Install Gdebi on your Ubuntu, run it, open DEB file and install it.

**Comment by chen-299** [comment]
> Install Gdebi on your Ubuntu, run it, open DEB file and install it.

I really appreciate your reply. 
I did these things：
#sudo apt-get install -y gdebi；
#sudo gdebi -n capanalysis_*.deb；
What is the meaning of “run it” ？

**Comment by MatejKovacic** [comment]
I would say that is it. Is there some "install" button somewhere? Can you checked capanaylsis is then actually installed on the system?

**Comment by chen-299** [comment]
Yes,I just meet the same problem as you：When I click to "Go to CapAnalysis UI", I got blank page.

**Comment by nachofest** [comment]
I have the same issue

**Comment by carlsue** [comment]
i have the same issue
