### ISSUE TITLE
the max files 

### ISSUE THREAD

**Issue by ethan76** [xplico/CapAnalysis#4]
capanalysis can analysis Maximum amount of data 13GB? when i upload the files more than 13GB, it can deal with 13GB，others can't be handled .what's the reason, is something wrong? thanks

**Comment by gnlcosta** [comment]
No, there aren't limits.
How you upload the pcap, from the web interface o directly in the dir?
is the 13G only in one file or split in more files?

**Comment by ethan76** [comment]
from the web interface, more files.
web interface display it Upload file continuously,but the amount of data(displayed  by web interface) can't increase.

**Comment by gnlcosta** [comment]
do you see the files names in the files list?
There is a PHP file size limit this for each single file, this limit is indicated in the web interface by "Max Size: " below the "CLICK HERE" button.
